### ISSUE TITLE
It is not possible to change the language to Russian (LG G Watch aka Dory)

### ISSUE THREAD

**Issue by Salat-Cx65** [AsteroidOS/asteroid-settings#6]
Steps to reproduce
- go to Settings/Languages
- choose "Русский"
- confirm and wait for start rebooting
- launch Asteroid OS 

Current: after reboot, OS use Franch localization
Expected: should be Russian localization loaded

**Comment by TheLastProject** [comment]
This is indeed the case with the release images on the website but the bug was fixed later. For now, you'll have to build a new image yourself (or get on IRC, someone may have a newer image built you could use)

On 17 February 2017 13:44:30 CET, Sergej Komlach <notifications@github.com> wrote:
>Steps to reproduce
>- go to Settings/Languages
>- choose "Русский"
>- confirm and wait for start rebooting
>- launch Asteroid OS 
>
>Current: after reboot, OS use Franch localization
>Expected: should be Russian localization loaded
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/AsteroidOS/asteroid-settings/issues/6

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
